### PR TITLE
Log a warning if the context is missing

### PR DESCRIPTION
**Pull request by JeremyEinfeld**
Rather than throwing an error (`Cannot read property 'announcePolite' of undefined`) if the context is missing, fall back to logging a warning.

### CODE REVIEW

**Comment by AlmeroSteyn** [comment]
@JeremyEinfeld Would you still like to complete this PR?

**Comment by JeremyEinfeld** [comment]
Yes, I'll try to push an update today.

**Comment by AlmeroSteyn** [comment]
Sorry for having taken long on this. Busy with some deadline driven stuff.

Thanks for the update. 

Here is the thing. I think my estimate to only show this warning in production is probably not good. I am concerned about systems that may not have `process.env` declared. So it is probably better to throw this warning in all modes. After all, if the context provider is not declared then it is pretty broken anyways.

Also, this will definitely need some test coverage.

As I have given you the runaround with the production / dev thing I will be more than happy to take over and get this published as I do not want to waste your time :-) 

However, if you are up to it to change that back and add some tests it would be greatly appreciated.

**Comment by AlmeroSteyn** [comment]
@JeremyEinfeld Thank you for sticking with this!

**Pull request merged**
