### PR TITLE
Introduce typings for exported components

### PR DESCRIPTION
**Pull request by jurokapsiar**
This PR introduces Typescript typings for exported compoents, props and context.

### CODE REVIEW

**Comment by AlmeroSteyn** [comment]
Hi @jurokapsiar. Thank you for your interest!

I would prefer the typings to be added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). 

Is there a reason to not prefer this?

**Comment by AlmeroSteyn** [comment]
@jurokapsiar I am moving the discussion about the live region location and clearing to #7 :-)

As for the typings. I understand that collocation is always handy. Only this project is not built in TypesScript. So I would still prefer this being offloaded to DefinitelyTyped, please.

Will also assist in things like importing the typings into WebStorm and such.

I am closing this one.

**Comment by jurokapsiar** [comment]
Understand. I will introduce the types in DefinitelyTyped. Thanks for your feedback!

**Comment by AlmeroSteyn** [comment]
@jurokapsiar Thank you for the interest! Looking forward to your feedback on the live region changes :-)

**Pull request closed without merging**
